language: python
python:
- '3.5'
- '3.3'
- '2.7'
- '2.6'
install: pip install -r requirements.txt
script: python test.py
deploy:
  provider: pypi
  user: alkov.pro
  password:
    secure: ejI4CjsydBFlbQIWS75c7CyJGZNv5l95ox332u7e/hMCwhPG2PoAtMA1OyurgTv6P2kYYQgPXcw970TgxRd+LF64ioh+df6qQ308/HXRdO2orSCGoIxLsQVycMEKeelSLzdLZ27u1VpWCPuPJrx7BMKdGCckEOaGBhJO0iK1p8R/7otGpYM2bp1jKd4BnGdHiM2bNCYp5ZuX2qMYxssl9Sz05aZZTrIH322W0JfUaE0Ru4UrIUYLR8QTF+YH/cxwjZ6eWURUvc5inp0jYhw7RFOIDNe1UtXmbIlzhPT16w1vsXW8Z8ThwnfNxXWPa/Z61xhuQv76TKFIcXv7kd6YNPX2SkKkbllsgklGrWUg4OYlo0ChWcYT5N9ksl+TwJlorOT1qDGygbD1+rD66d3IqYZfUZ5opAcQKzg9iYPZU3m/JinQvjJUD18yDEhdhGXE4EZTN/Gl5kGNh9fe2qKWZqPODhCgEBnD/HT3JLsaUHEdV5bpVGjSNqZIMWgrKzhndwu8z/lhuCenL0jq6excEHP/zyXjQHgcJD+nKt95sLnCPBNjYmB3Fy/2jfPeNM4ImdaygUOu9HxRB5DVT8iY1KJOVZMKxnBS3rXHfRCJgylkA0Gtwm1/RBqaY+6PHzPREJbZQNZaCN4tAyLMfWg2T4N+TPqs7ysu5oay/z8OKH4=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
